# Generated by Django 5.0.3 on 2024-03-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbiodata',
            name='reg_number',
            field=models.IntegerField(),
        ),
    ]
