# Generated by Django 5.0.3 on 2024-03-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_studentbiodata_reg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbiodata',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
